# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/nan/src/mysql-ios/mysql/cmake/compile_flags.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/nan/src/mysql-ios/mysql/extra/icu/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/nan/src/mysql-ios/mysql/extra/icu/source/common/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/nan/src/mysql-ios/mysql/extra/icu/source/i18n/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/nan/src/mysql-ios/mysql/extra/icu/source/stubdata/CMakeLists.txt))

/Users/nan/src/mysql-ios/cmake_build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.12.1/bin/cmake -H/Users/nan/src/mysql-ios/mysql -B/Users/nan/src/mysql-ios/cmake_build
